package br.com.mirante.domain.audit;

/**
 * Acoes que precisam deixar rastro. A lista e fechada de proposito: auditoria
 * com string livre vira lixo em tres meses.
 */
public enum AcaoAuditavel {

    LOGIN_OK,
    LOGIN_RECUSADO,
    LOGOUT,
    SENHA_TROCADA,
    USUARIO_CRIADO,
    USUARIO_DESATIVADO,

    TITULO_CRIADO,
    TITULO_PUBLICADO,
    TITULO_DESPUBLICADO,
    TITULO_BLOQUEADO_POR_DIREITO,

    LICENCA_CADASTRADA,
    LICENCA_COMPROVADA,
    LICENCA_RESCINDIDA,

    CANAL_NO_AR,
    CANAL_FORA_DO_AR,

    PLANO_CRIADO,
    ASSINATURA_ABERTA,
    ASSINATURA_CANCELADA,
    PAGAMENTO_CONFIRMADO,
    PAGAMENTO_RECUSADO,

    REPRODUCAO_AUTORIZADA,
    REPRODUCAO_RECUSADA,

    TENANT_ABERTO,
    TENANT_SUSPENSO,

    DADO_PESSOAL_EXPORTADO,
    DADO_PESSOAL_APAGADO
}
